# golangci-lint configuration v2
version: "2"

run:
  timeout: 5m
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  exclusions:
    paths:
      - "vendor/"
      - "testdata/"
  
  enable:
    # Default linters
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    
    # Code quality linters from original config
    - bodyclose
    - exhaustive
    - goconst
    - godot
    - gomoddirectives
    - goprintffuncname
    # - gosec # Temporarily disabled - too many false positives for file operations
    - misspell
    - nakedret
    # - nestif # Temporarily disabled - code complexity warnings
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wrapcheck